// This file is autogenerated. Changes will be overwritten.
#include "3AKAH6XLXN/moc_AppleCalendarAdapter.cpp"
#include "3AKAH6XLXN/moc_CalDAVClient.cpp"
#include "3AKAH6XLXN/moc_CalendarAdapter.cpp"
#include "3AKAH6XLXN/moc_GoogleCalendarAdapter.cpp"
#include "3AKAH6XLXN/moc_OutlookCalendarAdapter.cpp"
#include "PRMOGMWJPH/moc_CalendarManager.cpp"
#include "F2ESZRYZMC/moc_DatabaseManager.cpp"
